# Generated by Django 4.1.1 on 2022-09-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ',
            old_name='eaddress',
            new_name='eadress',
        ),
    ]
